export default{
    products:[{
        _id:'1',
        name:'Flourescent Sneakers',
        category: 'mens', 
        image: '../images/sneaker1.png',
        price: 350,
        brand:'Off-White',
        rating: 4.5,
        numReviews:10,
        countInStock:6,
    },
    {   _id: '2' ,
        name:'Track.2 Sneakers',
        category: 'mens', 
        image: '../images/sneaker2.png',
        price: 900,
        brand:'Balenciaga',
        rating: 5,
        numReviews:2,
        countInStock:4,
    },
    {   _id:'3',
        name:'Black Sneakers',
        category: 'mens', 
        image: '../images/sneaker3.png',
        price: 550,
        brand:'Moschino',
        rating: 4,
        numReviews:2,
        countInStock: 6,
    },
    {   _id:'4' ,
        name:'Low Vulcanized Leather Sneakers',
        category: 'mens', 
        image: '../images/sneaker4.png',
        price: 385,
        brand:'Off-White',
        rating: 4.5,
        numReviews:8,
        countInStock:4,
    },
    {   _id:'5' ,
        name:'Orange Sneakers',
        category: 'mens', 
        image: '../images/sneaker5.png',
        price: 600,
        brand:'Off-White',
        rating: 4.7,
        numReviews:7,
        countInStock:8,
    }
]
}